[build]
  # Sitio est√°tico en el root: no compila nada
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Si tus funciones usan estas libs, Netlify debe saber que son externas
  external_node_modules = ["pg", "bcryptjs", "jsonwebtoken", "nodemailer", "busboy"]

[build.environment]
  NODE_VERSION = "20"
