[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"   # hace bundle de ESM (.mjs)

[dev]
  command = "npm run build"
  port = 8888
  functionsPort = 9999

# Redirige /api/* hacia las functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
